# Generated by Django 6.0 on 2025-12-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joined_at',
        ),
    ]
