# Generated by Django 6.0 on 2026-01-05 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbankdetails',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], default='SAVINGS', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorbankdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbankdetails',
            name='branch_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='vendorbankdetails',
            name='ifsc_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendorbankdetails',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='employees.vendor'),
        ),
    ]
