# Generated by Django 6.0 on 2025-12-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_passwordresetotp_payment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
    ]
