from django.urls import path
from .views import (
    LoginAPIView,
    LogoutAPIView,
    ForgotPasswordAPIView,
    VerifyOTPAPIView,
    ResetPasswordAPIView,
    ChangePasswordAPIView,
    UserListCreateAPIView,
    UserDetailAPIView,
    VendorListCreateAPIView,
    VendorDetailAPIView,
    VendorBankDetailsAPIView,
    VendorExpensesAPIView,
    ExpenseCategoryListCreateAPIView,
    ExpenseAPIView,
    AllExpensesAPIView,
    PaymentListCreateAPIView,
    PaymentDetailAPIView,
    ProjectAPIView,
    ProjectExpensesAPIView,
    ExpenseCarryForwardAPIView,
    ExpenseReportExcelAPIView,
    ExpenseReportPDFAPIView,
    RecurringExpenseListCreateAPIView,
    RecurringExpenseDetailAPIView,
)

urlpatterns = [
    path("login/", LoginAPIView.as_view()),
    path("logout/", LogoutAPIView.as_view()),
    path("forgot-password/", ForgotPasswordAPIView.as_view()),
    path("verify-otp/", VerifyOTPAPIView.as_view()),
    path("reset-password/", ResetPasswordAPIView.as_view()),
    path("change-password/", ChangePasswordAPIView.as_view()),
    path("users/", UserListCreateAPIView.as_view()),
    path("users/<int:pk>/", UserDetailAPIView.as_view()),
    path("vendors/", VendorListCreateAPIView.as_view()),
    path("vendors/<int:pk>/", VendorDetailAPIView.as_view()),
    path("vendors/<int:pk>/expenses/", VendorExpensesAPIView.as_view()),
    path("vendors/<int:vendor_id>/bank-details/", VendorBankDetailsAPIView.as_view()),
    path("vendors/bank-details/<int:pk>/", VendorBankDetailsAPIView.as_view()),
    path("recurring-expenses/", RecurringExpenseListCreateAPIView.as_view()),
    path("recurring-expenses/<int:pk>/", RecurringExpenseDetailAPIView.as_view()),
    path("categories/", ExpenseCategoryListCreateAPIView.as_view()),
    path("expenses/", ExpenseAPIView.as_view()),
    path("expenses/<int:pk>/", ExpenseAPIView.as_view()),
    path("expenses/all/", AllExpensesAPIView.as_view()),
    path("payments/", PaymentListCreateAPIView.as_view()),
    path("payments/<int:pk>/", PaymentDetailAPIView.as_view()),
    path("projects/", ProjectAPIView.as_view()),
    path("projects/<int:pk>/", ProjectAPIView.as_view()),
    path("projects/<int:pk>/expenses/", ProjectExpensesAPIView.as_view()),
    path("expenses/carry-forward/", ExpenseCarryForwardAPIView.as_view()),
    path("reports/excel/", ExpenseReportExcelAPIView.as_view()),
    path("reports/pdf/", ExpenseReportPDFAPIView.as_view()),
]
